### ISSUE TITLE
wonderful codes

### ISSUE THREAD

**Issue by chenmozxh** [fartashf/vsepp#15]
wonderful codes!!!
line 214-218 in model.py may be modified to:
out = torch.unsqueeze(torch.squeeze(_), 1)

**Comment by fartashf** [comment]
Not sure how you can do so. [Lines 214-218](https://github.com/fartashf/vsepp/blob/f2971a09b9f49f3814fa80701dcb1d2d3125da53/model.py#L214-L218) take the hiddens of the RNN and extract the last hiddens for sequence. `out` is PackedSequence object and `I` is a tensor with indices of the last hiddens.
