### ISSUE TITLE
problem in finetune

### ISSUE THREAD

**Issue by 136823xuewei** [fartashf/vsepp#18]
I use the original flickr30k dataset rather than precomputed features ,and use the pretrained model resnet50.I set finetune True. But, i get poor result of recall. R@1,R@5,R@10 is nearly zero.I can't find the reason about the bad result.How do you set the parameters when you use resnet with finetune?
Thank you.

**Comment by fartashf** [comment]
Try learning rate 0.00002. Look at section 3.2 for more details of training.

**Comment by 136823xuewei** [comment]
Thanks for your reply!

**Comment by LightGal** [comment]
@136823xuewei  Did you succeed in getting good results using raw images and finetuning rather than using precomputed features?

@fartashf  I trained on the COCO dataset without precomputed features but failed to get good results (@1 less than 1.). Using precomputed features is all good.

The learning rate is 0.00002 when training on raw images.

Could someone help me?

**Comment by fartashf** [comment]
I can still reproduce the result of the following command using the latest commit on the master:
```
python train.py --data_name coco --logger_name runs/X --max_violation
```

It takes at least 1000 iterations to reach above 1% R@1 that is expected.

By default the learning rate is 0.0002. I reproduced it using python 2.7.14 and pytorch 0.3.1. For python 3 and pytorch 1 checkout the details on their corresponding branches.

**Comment by winnechan** [comment]
if we fix the image full encoder in the first epoch and train the joint embedding model, do we need to write some code to force the image cnn encoder always in evaluation mode? i.e. no dropout and ...

**Comment by nattari** [comment]
I would like to fine-tune the model on my dataset, I use the following command:
`python train.py --finetune --max_violation --batch_size 32 --cnn_type resnet152 --resume runs/coco_vse++_resnet_restval_finetune/model_best.pth.tar `

But this doesn't seem to work, I get the following error:
`Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main()
  File "train.py", line 103, in main
    model.load_state_dict(checkpoint['model'])
  File "/home/nattari/dsg_projects/project_na/vsepp/model.py", line 336, in load_state_dict
    self.txt_enc.load_state_dict(state_dict[1])
  File "/home/nattari/anaconda3/envs/vsepp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EncoderText:
	size mismatch for embed.weight: copying a param of torch.Size([1180, 300]) from checkpoint, where the shape is torch.Size([11755, 300]) in current model.`
	
Probably I am missing something here. Could you provide some insights?
