### ISSUE TITLE
How to get coco_train_ids.npy?

### ISSUE THREAD

**Issue by MaAo** [fartashf/vsepp#22]
I want to train "coco" instead of "coco_precomp", but the file indicated by "download.sh":

http://msvocds.blob.core.windows.net/annotations-1-0-3/captions_train-val2014.zip

doesn't contain the coco_train/val/test_ids.npy files and I encountered
No such file or directory: vsepp/data/coco/annotations/coco_train_ids.npy

So where to get these files in order to train "coco"?

Thanks in advance.

**Comment by MaAo** [comment]
And I‘ve not find coco_train_ids.npy in https://cs.stanford.edu/people/karpathy/deepimagesent/.
Can someone help?

**Comment by fartashf** [comment]
The annotation files are included in the data archive located here:
http://www.cs.toronto.edu/~faghri/vsepp/data.tar

**Comment by zzwDL** [comment]
> 注释文件包含在位于此处的数据存档中： [http ://www.cs.toronto.edu/~faghri/vsepp/data.tar](http://www.cs.toronto.edu/~faghri/vsepp/data.tar)

Sorry to bother you. This download link is invalid. Can you provide it again? Thank you very much！

**Comment by fartashf** [comment]
The link you quoted has an extra space before the colon. This link is working:
http://www.cs.toronto.edu/~faghri/vsepp/data.tar
