### ISSUE TITLE
Train on other language dataset

### ISSUE THREAD

**Issue by Hanzhanghub** [fartashf/vsepp#23]
Hi, thanks for releasing the great work！
Sorry to bother you, but can this model be applied to other languages' caption datasets ?

Thanks for your reply!

**Comment by fartashf** [comment]
This model can be used for any image-caption retrieval task. You can use it if you have a fixed set of captions to choose from. It can also be used in combination with a method that generates caption proposals.
Did you have a specific dataset in mind?

**Comment by Hanzhanghub** [comment]
Thanks for the reply!
I will try it on my own dataset.
