### ISSUE TITLE
Metrics for 1k test images on MS COCO

### ISSUE THREAD

**Issue by chinmay5** [fartashf/vsepp#26]
I am sorry to create a new issue but I think this way it would be better since the doubt might be shared by a few other people.

**Just to confirm, we evaluate on the 5 folds and report the best result on one of these samples(the best performing 1k sample) or we report the average value for all 5 sets? If the result is for the best performing 1k sample, is it not kind of "pick and choose" scenario?**

Honestly, this is a wonderful code base and I think this is the most likely place to find a solution to my doubts :)

**Comment by fartashf** [comment]
The metrics reported for the 1K results are averaged over 5 splits. Here is the line that does it:
https://github.com/fartashf/vsepp/blob/226688a0f26aa1c32d34fbe723795dc65702504c/evaluation.py#L193
