### ISSUE TITLE
How to build vocab?

### ISSUE THREAD

**Issue by chwlsunny** [fartashf/vsepp#29]
Hello fartashf, your code is very helpful for me, but I am confused when I read the python script of **vocab.py**.  When you construct the vocab of **f8k_precomp**, you use the **train captions** and **valid captions**. But when you construct the vocab of **f8k,** you use the **train captions**, **valid captions** and **test caption**s. Could you explain it?

**Comment by fartashf** [comment]
Are you referring to this function?
https://github.com/fartashf/vsepp/blob/226688a0f26aa1c32d34fbe723795dc65702504c/vocab.py#L55

I think that's a bug. we should not build the vocab using test captions. Thanks for reporting.

**Comment by chwlsunny** [comment]
> Are you referring to this function?
> https://github.com/fartashf/vsepp/blob/226688a0f26aa1c32d34fbe723795dc65702504c/vocab.py#L55
> 
> I think that's a bug. we should not build the vocab using test captions. Thanks for reporting.

Yeah, I am referring to this function. Thanks for your considerate replies.
