### ISSUE TITLE
about use dataset

### ISSUE THREAD

**Issue by zhangchubing** [fartashf/vsepp#37]
Hi,I have a question about use dataset,For coco I use it to make classfication,I make images dimension to 80,then use labels to supervise it,but the performance is not good.,I will appreciate it if you could give some advices.

**Comment by fartashf** [comment]
There seems to be a number of factors different in your setting that the intended use of this project. In particular, it is not clear how you get supervision for training the model. You might want to consider using other open source codes. Or provide more information here.
