### ISSUE TITLE
Runs file too large

### ISSUE THREAD

**Issue by JoanFM** [fartashf/vsepp#38]
Hey @fartashf 

I would like to ask you if it would be possible to split the `runs.tar` and `vocab.tar` into smaller pieces per type of model.
I am trying to download them and remove the models that I do not need when I create some docker images, and I think it would make the usage much easier and lighter.

Thank you very much

**Comment by fartashf** [comment]
Hi Joan,

Sorry for late reply. Is this still an issue for you?

I understand that the files are big (`runs.tar` is 7G and `data.tar` is 12G). At the same time, downloading them all of the runs and data seems to be the common use-case. Unfortunately, I don't have much space on the server to host duplicate copies.

Have you considered cloning the particular runs you are frequently accessing to another server?
