### ISSUE TITLE
Same meanr being logged by tb_logger during validation

### ISSUE THREAD

**Issue by averyma** [fartashf/vsepp#42]
Hello Fartash,

A small issue that I noticed: there is no `meanri` for `t2i` and the same `meanr` from `i2t` is being logged by the tb_logger during validation.

https://github.com/fartashf/vsepp/blob/cb5561a5dc745bf495729b261a97e0c93ef0203f/train.py#L209

and 

https://github.com/fartashf/vsepp/blob/cb5561a5dc745bf495729b261a97e0c93ef0203f/train.py#L214

Awesome work and hats off to you for still maintaining the repo.

Regards,
Avery

**Comment by fartashf** [comment]
Hi Avery,

Good catch. Thanks. The printed statements were correct but the ones logged using `tb_logger` were wrong. Commit 7f8ffd55bf4c5f195fcae543f9b8e242e665d839  has fix that. We did not report `meanr`, `meanri` in the paper so the change does not concern the numbers in the paper.

Thank you for reporting the issue and using the code.

Fartash
