### ISSUE TITLE
The number of COCO validation images

### ISSUE THREAD

**Issue by KevinLight831** [fartashf/vsepp#44]
In the COCO dataset, the number of validation images is 1000, but I found many papers claimed the number is 5000.

**Comment by fartashf** [comment]
There are 5000 test images as well as more than 5000 validation images in the original split of MSCOCO. Please see Section 3.1 of the paper for the details and references (https://arxiv.org/pdf/1707.05612.pdf) and the corresponding lines in the code:
https://github.com/fartashf/vsepp/blob/7f8ffd55bf4c5f195fcae543f9b8e242e665d839/data.py#L51-L59
