### ISSUE TITLE
Question about your model ?

### ISSUE THREAD

**Issue by ThorPham** [fartashf/vsepp#46]
I have a question about your model. I have a image with pill object and list of text is name of pill  corresponding to image. I want to map pill object and name of it.  Because number pill classes very huge so I know some prior infomation about classes . 
I have train faster RCNN to detect pill and now i must map it with name. Is your model is relavent to this problem.  Thank you so much

**Comment by fartashf** [comment]
Sorry for the delayed response. It is possible to cast a classification problem into contrastive learning. The captions would be the classes. Another option is classification with more scalable variants of softmax, e.g. https://arxiv.org/abs/1609.04309.
