### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4608x2048 and 4096x1024)

### ISSUE THREAD

**Issue by frozen30** [fartashf/vsepp#49]
Hello, I encountered the following problems during the test:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4608x2048 and 4096x1024)
I checked the parameters of the model and found that 1024 is emb_size, 4096 is img_size, and 4608x2048 refers to the size of the [128, 36, 2048] image.
How can I solve this problem?

**Comment by fartashf** [comment]
Can you provide more details as how you run the code and the stack trace for this error?
