### ISSUE TITLE
how to get coco_precomp_vocab.pkl?

### ISSUE THREAD

**Issue by chirstinaFan** [fartashf/vsepp#7]
I can not open this file.Can you tell me how to build it?

**Comment by fartashf** [comment]
You can simply download the vocabularies from here:
http://www.cs.toronto.edu/~faghri/vsepp/vocab.tar

Please refer to the instructions in the section "Download Data" in the readme file.

**Comment by chirstinaFan** [comment]
I want to know when I use my data,how to build our vocab.pkl?

**Comment by fartashf** [comment]
You would need to modify and run `vocab.py`. Look at the how supported datasets are handled in that file.
https://github.com/fartashf/vsepp/blob/master/vocab.py
